# ============================================
# Predictive Maintenance MLOps Configuration
# ============================================

project:
  name: "Predictive Maintenance MLOps"
  version: "1.0"

# -------------------------
# Data Configuration
# -------------------------
data:
  raw_path: "data/raw/sensor_data.csv"
  processed_path: "data/processed/processed_data.csv"

# -------------------------
# Model Configuration
# -------------------------
model:
  model_path: "models/predictive_model.pkl"
  n_estimators: 100
  max_depth: 5
  random_state: 42

# -------------------------
# MLflow Tracking
# -------------------------
mlflow:
  tracking_uri: "http://127.0.0.1:5000"
  experiment_name: "Predictive Maintenance Experiments"

# -------------------------
# Training Parameters
# -------------------------
training:
  test_size: 0.2
  validation_split: 0.1
  random_state: 42

# -------------------------
# API Configuration
# -------------------------
api:
  host: "127.0.0.1"
  port: 8000
  reload: true
