name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run tests
        run: pytest -v

      - name: Build Docker image
        run: docker build -t predictive-maintenance-api .

      - name: Log in to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to DockerHub
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag predictive-maintenance-api ${{ secrets.DOCKERHUB_USERNAME }}/predictive-maintenance-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/predictive-maintenance-api:latest
